-- MySQL Script generated by MySQL Workbench
-- di 28 aug 2018 10:29:16 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema COGIP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema COGIP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `COGIP` DEFAULT CHARACTER SET utf8 ;
USE `COGIP` ;

-- -----------------------------------------------------
-- Table `COGIP`.`type_soc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COGIP`.`type_soc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COGIP`.`societe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COGIP`.`societe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `pays` VARCHAR(45) NULL,
  `tva` VARCHAR(20) NULL,
  `telephone` INT NULL,
  `type_soc_id` INT NOT NULL,
  PRIMARY KEY (`id`, `type_soc_id`),
  INDEX `fk_societe_type_soc_idx` (`type_soc_id` ASC),
  CONSTRAINT `fk_societe_type_soc`
    FOREIGN KEY (`type_soc_id`)
    REFERENCES `COGIP`.`type_soc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COGIP`.`personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COGIP`.`personne` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `telephone` INT NULL,
  `email` VARCHAR(45) NULL,
  `societe_id` INT NOT NULL,
  `societe_type_soc_id` INT NOT NULL,
  PRIMARY KEY (`id`, `societe_id`, `societe_type_soc_id`),
  INDEX `fk_personne_societe1_idx` (`societe_id` ASC, `societe_type_soc_id` ASC),
  CONSTRAINT `fk_personne_societe1`
    FOREIGN KEY (`societe_id` , `societe_type_soc_id`)
    REFERENCES `COGIP`.`societe` (`id` , `type_soc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COGIP`.`facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COGIP`.`facture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NULL,
  `date_facturation` DATE NULL,
  `motif_prestation` MEDIUMTEXT NULL,
  `societe_id` INT NOT NULL,
  `societe_type_soc_id` INT NOT NULL,
  `personne_id` INT NOT NULL,
  `personne_societe_id` INT NOT NULL,
  `personne_societe_type_soc_id` INT NOT NULL,
  PRIMARY KEY (`id`, `societe_id`, `societe_type_soc_id`, `personne_id`, `personne_societe_id`, `personne_societe_type_soc_id`),
  INDEX `fk_facture_societe1_idx` (`societe_id` ASC, `societe_type_soc_id` ASC),
  INDEX `fk_facture_personne1_idx` (`personne_id` ASC, `personne_societe_id` ASC, `personne_societe_type_soc_id` ASC),
  CONSTRAINT `fk_facture_societe1`
    FOREIGN KEY (`societe_id` , `societe_type_soc_id`)
    REFERENCES `COGIP`.`societe` (`id` , `type_soc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facture_personne1`
    FOREIGN KEY (`personne_id` , `personne_societe_id` , `personne_societe_type_soc_id`)
    REFERENCES `COGIP`.`personne` (`id` , `societe_id` , `societe_type_soc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
